#!/bin/bash
#
# Title:      MariaDB
# Author(s):  MariaDB Foundation
# URL:        https://mariadb.com - https://github.com/docker-library/mariadb
# GNU:        General Public License v2.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
# CORE (MANDATORY) DO NOT CHANGE ###########################################

    - name: 'Set Known Facts'
      set_fact:
        pgrole: "freepbx-db"
        intport: "3306"
        extport: "3306"
        image: "tiredofit/mariadb"

    - name: 'Including cron job'
      include_tasks: '/opt/communityapps/apps/_core.yml'

# LABELS ################################################################
    

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/opt/appdata/{{pgrole}}:/var/lib/mysql'
          - '/etc/localtime:/etc/localtime:ro'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: asterisk
          MYSQL_USER: asterisk
          MYSQL_PASSWORD: asteriskpass

    # MAIN DEPLOYMENT ##############################################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        expose: 3306
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started
        labels: '{{pg_labels}}'

    # POST DEPLOYMENT ##############################################################

    - name: 'Post Deployment Notes'
      debug:
        msg: |-
          * Login Information *  * This should be changed *
