#!/bin/bash
#
# Title:      FreePBX
# Author(s):  FreePBX
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
# CORE (MANDATORY) DO NOT CHANGE ###########################################

    - name: 'Set Known Facts'
      set_fact:
        pgrole: "freepbx-app"
        intport: "80"
        extport: "8001"
        intport2: "8003"
        extport2: "8003"
        intport3: "4445"
        extport3: "4445"
        intport4: "18100/udp"
        extport4: "18000"
        extport5: "18001"
        extport6: "18002"
        extport7: "18003"
        extport8: "18004"
        extport9: "18005"
        extport10: "18006"
        extport11: "18007"
        extport12: "18008"
        extport13: "18009"
        extport14: "18010"
        extport15: "18011"
        extport16: "18012"
        extport17: "18013"
        extport18: "18014"
        extport19: "18015"
        extport20: "18016"
        extport21: "18017"
        extport22: "18018"
        extport23: "18019"
        extport24: "18020"
        extport25: "18021"
        extport26: "18022"
        extport27: "18023"
        extport28: "18024"
        extport29: "18025"
        extport30: "18026"
        extport31: "18027"
        extport32: "18028"
        extport33: "18029"
        extport34: "18030"
        extport35: "18031"
        extport36: "18032"
        extport37: "18033"
        extport38: "18034"
        extport39: "18035"
        extport40: "18036"
        extport41: "18037"
        extport42: "18038"
        extport43: "18039"
        extport44: "18040"
        extport45: "18041"
        extport46: "18042"
        extport47: "18043"
        extport48: "18044"
        extport49: "18045"
        extport50: "18046"
        extport51: "18047"
        extport52: "18048"
        extport53: "18049"
        extport54: "18050"
        extport55: "18051"
        extport56: "18052"
        extport57: "18053"
        extport58: "18054"
        extport59: "18055"
        extport60: "18056"
        extport61: "18057"
        extport62: "18058"
        extport63: "18059"
        extport64: "18060"
        extport65: "18061"
        extport66: "18062"
        extport67: "18063"
        extport68: "18064"
        extport69: "18065"
        extport70: "18066"
        extport71: "18067"
        extport72: "18068"
        extport73: "18069"
        extport74: "18070"
        extport75: "18071"
        extport76: "18072"
        extport77: "18073"
        extport78: "18074"
        extport79: "18075"
        extport80: "18076"
        extport81: "18077"
        extport82: "18078"
        extport83: "18079"
        extport84: "18080"
        extport85: "18081"
        extport86: "18082"
        extport87: "18083"
        extport88: "18084"
        extport89: "18085"
        extport90: "18086"
        extport91: "18087"
        extport92: "18088"
        extport93: "18089"
        extport94: "18090"
        extport95: "18091"
        extport96: "18092"
        extport97: "18093"
        extport98: "18094"
        extport99: "18095"
        extport100: "18096"
        extport101: "18097"
        extport102: "18098"
        extport103: "18099"
        extport104: "18100"
        intport5: "18001/udp"
        intport6: "18002/udp"
        intport7: "18003/udp"
        intport8: "18004/udp"
        intport9: "18005/udp"
        intport10: "18006/udp"
        intport11: "18007/udp"
        intport12: "18008/udp"
        intport13: "18009/udp"
        intport14: "18010/udp"
        intport15: "18011/udp"
        intport16: "18012/udp"
        intport17: "18013/udp"
        intport18: "18014/udp"
        intport19: "18015/udp"
        intport20: "18016/udp"
        intport21: "18017/udp"
        intport22: "18018/udp"
        intport23: "18019/udp"
        intport24: "18020/udp"
        intport25: "18021/udp"
        intport26: "18022/udp"
        intport27: "18023/udp"
        intport28: "18024/udp"
        intport29: "18025/udp"
        intport30: "18026/udp"
        intport31: "18027/udp"
        intport32: "18028/udp"
        intport33: "18029/udp"
        intport34: "18030/udp"
        intport35: "18031/udp"
        intport36: "18032/udp"
        intport37: "18033/udp"
        intport38: "18034/udp"
        intport39: "18035/udp"
        intport40: "18036/udp"
        intport41: "18037/udp"
        intport42: "18038/udp"
        intport43: "18039/udp"
        intport44: "18040/udp"
        intport45: "18041/udp"
        intport46: "18042/udp"
        intport47: "18043/udp"
        intport48: "18044/udp"
        intport49: "18045/udp"
        intport50: "18046/udp"
        intport51: "18047/udp"
        intport52: "18048/udp"
        intport53: "18049/udp"
        intport54: "18050/udp"
        intport55: "18051/udp"
        intport56: "18052/udp"
        intport57: "18053/udp"
        intport58: "18054/udp"
        intport59: "18055/udp"
        intport60: "18056/udp"
        intport61: "18057/udp"
        intport62: "18058/udp"
        intport63: "18059/udp"
        intport64: "18060/udp"
        intport65: "18061/udp"
        intport66: "18062/udp"
        intport67: "18063/udp"
        intport68: "18064/udp"
        intport69: "18065/udp"
        intport70: "18066/udp"
        intport71: "18067/udp"
        intport72: "18068/udp"
        intport73: "18069/udp"
        intport74: "18070/udp"
        intport75: "18071/udp"
        intport76: "18072/udp"
        intport77: "18073/udp"
        intport78: "18074/udp"
        intport79: "18075/udp"
        intport80: "18076/udp"
        intport81: "18077/udp"
        intport82: "18078/udp"
        intport83: "18079/udp"
        intport84: "18080/udp"
        intport85: "18081/udp"
        intport86: "18082/udp"
        intport87: "18083/udp"
        intport88: "18084/udp"
        intport89: "18085/udp"
        intport90: "18086/udp"
        intport91: "18087/udp"
        intport92: "18088/udp"
        intport93: "18089/udp"
        intport94: "18090/udp"
        intport95: "18091/udp"
        intport96: "18092/udp"
        intport97: "18093/udp"
        intport98: "18094/udp"
        intport99: "18095/udp"
        intport100: "18096/udp"
        intport101: "18097/udp"
        intport102: "18098/udp"
        intport103: "18099/udp"
        intport104: "18100/udp"
        intport105: "5060"
        extport105: "5060"
        intport106: "5160"
        extport106: "5160"
        intport107: "8008"
        extport107: "8008"
        image: "tiredofit/freepbx"

    - name: 'Including cron job'
      include_tasks: '/opt/communityapps/apps/_core.yml'

# LABELS ################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.enable: 'true'
          traefik.port: '80'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}},{{tldset}}'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/opt/appdata/{{pgrole}}/certs:/certs'
          - '/opt/appdata/{{pgrole}}/data:/data'
          - '/opt/appdata/{{pgrole}}/logs:/var/log'
          - '/opt/appdata/{{pgrole}}/data/www:/var/www/html'
          - '/etc/localtime:/etc/localtime:ro'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          ZABBIX_HOSTNAME: freepbx-app
          RTP_START: 18000
          RTP_FINISH: 18100
          DB_EMBEDDED: FALSE
          DB_HOST: freepbx-db
          DB_PORT: 3306
          DB_NAME: asterisk
          DB_USER: asterisk
          DB_PASS: asteriskpass
          ENABLE_FAIL2BAN: FALSE

    # MAIN DEPLOYMENT ##############################################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
          - '{{ports.stdout}}{{extport2}}:{{intport2}}'
          - '{{ports.stdout}}{{extport3}}:{{intport3}}'
          - '{{extport4}}:{{intport4}}'
          - '{{extport5}}:{{intport5}}'
          - '{{extport6}}:{{intport6}}'
          - '{{extport7}}:{{intport7}}'
          - '{{extport8}}:{{intport8}}'
          - '{{extport9}}:{{intport9}}'
          - '{{extport10}}:{{intport10}}'
          - '{{extport11}}:{{intport11}}'
          - '{{extport12}}:{{intport12}}'
          - '{{extport13}}:{{intport13}}'
          - '{{extport14}}:{{intport14}}'
          - '{{extport15}}:{{intport15}}'
          - '{{extport16}}:{{intport16}}'
          - '{{extport17}}:{{intport17}}'
          - '{{extport18}}:{{intport18}}'
          - '{{extport19}}:{{intport19}}'
          - '{{extport20}}:{{intport20}}'
          - '{{extport21}}:{{intport21}}'
          - '{{extport22}}:{{intport22}}'
          - '{{extport23}}:{{intport23}}'
          - '{{extport24}}:{{intport24}}'
          - '{{extport25}}:{{intport25}}'
          - '{{extport26}}:{{intport26}}'
          - '{{extport27}}:{{intport27}}'
          - '{{extport28}}:{{intport28}}'
          - '{{extport29}}:{{intport29}}'
          - '{{extport30}}:{{intport30}}'
          - '{{extport31}}:{{intport31}}'
          - '{{extport32}}:{{intport32}}'
          - '{{extport33}}:{{intport33}}'
          - '{{extport34}}:{{intport34}}'
          - '{{extport35}}:{{intport35}}'
          - '{{extport36}}:{{intport36}}'
          - '{{extport37}}:{{intport37}}'
          - '{{extport38}}:{{intport38}}'
          - '{{extport39}}:{{intport39}}'
          - '{{extport40}}:{{intport40}}'
          - '{{extport41}}:{{intport41}}'
          - '{{extport42}}:{{intport42}}'
          - '{{extport43}}:{{intport43}}'
          - '{{extport44}}:{{intport44}}'
          - '{{extport45}}:{{intport45}}'
          - '{{extport46}}:{{intport46}}'
          - '{{extport47}}:{{intport47}}'
          - '{{extport48}}:{{intport48}}'
          - '{{extport49}}:{{intport49}}'
          - '{{extport50}}:{{intport50}}'
          - '{{extport51}}:{{intport51}}'
          - '{{extport52}}:{{intport52}}'
          - '{{extport53}}:{{intport53}}'
          - '{{extport54}}:{{intport54}}'
          - '{{extport55}}:{{intport55}}'
          - '{{extport56}}:{{intport56}}'
          - '{{extport57}}:{{intport57}}'
          - '{{extport58}}:{{intport58}}'
          - '{{extport59}}:{{intport59}}'
          - '{{extport60}}:{{intport60}}'
          - '{{extport61}}:{{intport61}}'
          - '{{extport62}}:{{intport62}}'
          - '{{extport63}}:{{intport63}}'
          - '{{extport64}}:{{intport64}}'
          - '{{extport65}}:{{intport65}}'
          - '{{extport66}}:{{intport66}}'
          - '{{extport67}}:{{intport67}}'
          - '{{extport68}}:{{intport68}}'
          - '{{extport69}}:{{intport69}}'
          - '{{extport70}}:{{intport70}}'
          - '{{extport71}}:{{intport71}}'
          - '{{extport72}}:{{intport72}}'
          - '{{extport73}}:{{intport73}}'
          - '{{extport74}}:{{intport74}}'
          - '{{extport75}}:{{intport75}}'
          - '{{extport76}}:{{intport76}}'
          - '{{extport77}}:{{intport77}}'
          - '{{extport78}}:{{intport78}}'
          - '{{extport79}}:{{intport79}}'
          - '{{extport80}}:{{intport80}}'
          - '{{extport81}}:{{intport81}}'
          - '{{extport82}}:{{intport82}}'
          - '{{extport83}}:{{intport83}}'
          - '{{extport84}}:{{intport84}}'
          - '{{extport85}}:{{intport85}}'
          - '{{extport86}}:{{intport86}}'
          - '{{extport87}}:{{intport87}}'
          - '{{extport88}}:{{intport88}}'
          - '{{extport89}}:{{intport89}}'
          - '{{extport90}}:{{intport90}}'
          - '{{extport91}}:{{intport91}}'
          - '{{extport92}}:{{intport92}}'
          - '{{extport93}}:{{intport93}}'
          - '{{extport94}}:{{intport94}}'
          - '{{extport95}}:{{intport95}}'
          - '{{extport96}}:{{intport96}}'
          - '{{extport97}}:{{intport97}}'
          - '{{extport98}}:{{intport98}}'
          - '{{extport99}}:{{intport99}}'
          - '{{extport100}}:{{intport100}}'
          - '{{extport101}}:{{intport101}}'
          - '{{extport102}}:{{intport102}}'
          - '{{extport103}}:{{intport103}}'
          - '{{extport104}}:{{intport104}}'
          - '{{extport105}}:{{intport105}}'
          - '{{extport106}}:{{intport106}}'
          - '{{ports.stdout}}{{extport107}}:{{intport107}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started
        labels: '{{pg_labels}}'

    # POST DEPLOYMENT ##############################################################

    - name: 'Post Deployment Notes'
      debug:
        msg: |-
          * Login Information *  * This should be changed *
